[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
user=root

[program:web]
command=/opt/venv/bin/gunicorn qsts3.wsgi:application --bind 0.0.0.0:8000 --workers 2 --access-logfile - --error-logfile - --capture-output
directory=/app
environment=PYTHONPATH="/app/src",DJANGO_SETTINGS_MODULE="qsts3.settings"
user=qs3
autostart=true
autorestart=unexpected
startretries=3
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:batch-worker]
command=/opt/venv/bin/python /app/src/manage.py send_batches
directory=/app
environment=PYTHONPATH="/app/src",DJANGO_SETTINGS_MODULE="qsts3.settings"
user=qs3
autostart=true
autorestart=unexpected
startretries=3
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
