<?php
// Disposable integration-test configuration; never used by normal installations.
$wgSitename = 'Bulk import test';
$wgServer = 'http://bulk.test';
$wgScriptPath = '/w';
$wgArticlePath = '/wiki/$1';
$wgDBtype = 'mysql';
$wgDBserver = 'mysql';
$wgDBname = 'bulk_test';
$wgDBuser = 'bulk_test';
$wgDBpassword = 'bulk-test-only';
$wgSecretKey = 'bulk-import-integration-test-only';
$wgLanguageCode = 'en';
$wgMainCacheType = CACHE_NONE;
$wgJobRunRate = 0;
$wgShowExceptionDetails = true;
$wgEnableWikibaseRepo = true;
$wgEnableWikibaseClient = false;
wfLoadExtension( 'WikibaseRepository', "$IP/extensions/Wikibase/extension-repo.json" );
require "$IP/extensions/Wikibase/repo/ExampleSettings.php";
$wgWBRepoSettings['conceptBaseUri'] = 'http://bulk.test/entity/';
wfLoadExtension( 'Elastica' );
wfLoadExtension( 'CirrusSearch' );
wfLoadExtension( 'WikibaseCirrusSearch' );
$wgSearchType = 'CirrusSearch';
$wgCirrusSearchServers = [ 'search' ];
$wgCirrusSearchClusters = [ 'default' => [ 'search' ] ];
$wgCirrusSearchExtraIndexSettings['index.mapping.total_fields.limit'] = 5000;
$wgCirrusSearchDisableUpdate = getenv( 'WBS_DISABLE_CIRRUS_UPDATES' ) === '1';
$wgWBCSUseCirrus = true;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createaccount'] = false;
