<?php

declare( strict_types=1 );

require dirname( __DIR__ ) . '/Configuration.php';

function readJsonObject( string $path ): array {
	$contents = file_get_contents( $path );
	if ( $contents === false ) {
		fail( "Could not read $path." );
	}
	$start = strpos( $contents, '{' );
	$end = strrpos( $contents, '}' );
	if ( $start === false || $end === false || $end < $start ) {
		fail( "No JSON object was found in $path." );
	}
	$data = json_decode( substr( $contents, $start, $end - $start + 1 ), true );
	if ( !is_array( $data ) ) {
		fail( "Could not decode the configuration in $path." );
	}
	return $data;
}

function legacyElasticsearchHost( string $source ): ?string {
	if ( preg_match(
		'/\$elasticsearchHost\s*=\s*([\'\"])(.*?)\1\s*;/',
		$source,
		$matches
	) ) {
		return stripcslashes( $matches[2] );
	}
	return null;
}

function assignmentsInSourceOrder( string $source ): array {
	$tokens = token_get_all( $source );
	$assignments = [];
	$count = count( $tokens );
	for ( $i = 0; $i < $count; $i++ ) {
		$token = $tokens[$i];
		if ( !is_array( $token ) || $token[0] !== T_VARIABLE || !str_starts_with( $token[1], '$wg' ) ) {
			continue;
		}
		$name = substr( $token[1], 1 );
		$statement = $token[1];
		$hasAssignment = false;
		$depth = 0;
		for ( $j = $i + 1; $j < $count; $j++ ) {
			$text = is_array( $tokens[$j] ) ? $tokens[$j][1] : $tokens[$j];
			$statement .= $text;
			if ( $depth === 0 && in_array(
				$text,
				[ '=', '+=', '-=', '*=', '/=', '.=', '%=', '&=', '|=', '^=', '<<=', '>>=', '??=' ],
				true
			) ) {
				$hasAssignment = true;
			}
			if ( in_array( $text, [ '[', '(', '{' ], true ) ) {
				$depth++;
			} elseif ( in_array( $text, [ ']', ')', '}' ], true ) ) {
				$depth--;
			} elseif ( $text === ';' && $depth === 0 ) {
				if ( $hasAssignment ) {
					$assignments[] = [ 'name' => $name, 'source' => trim( $statement ) ];
				}
				$i = $j;
				break;
			}
		}
	}
	return $assignments;
}

function legacyGeneratedMarkerPosition( string $source ): int {
	if ( !preg_match( '/^# End of generated LocalSettings\.php\r?$/m', $source, $match, PREG_OFFSET_CAPTURE ) ) {
		fail( 'The legacy LocalSettings.php does not contain the expected generated marker.' );
	}
	return $match[0][1];
}

/** Significant tokens retain their source offsets so only the loader is replaced. */
function legacyTokens( string $source ): array {
	$result = [];
	$offset = 0;
	$depth = 0;
	foreach ( token_get_all( $source ) as $token ) {
		$text = is_array( $token ) ? $token[1] : $token;
		$end = $offset + strlen( $text );
		if ( !is_array( $token ) || !in_array( $token[0], [ T_OPEN_TAG, T_WHITESPACE, T_COMMENT, T_DOC_COMMENT ], true ) ) {
			$value = $text;
			if ( is_array( $token ) && $token[0] === T_CONSTANT_ENCAPSED_STRING ) {
				// The known paths have no escapes or interpolation; accept either quote style.
				$value = "'" . substr( $text, 1, -1 ) . "'";
			}
			$result[] = [
				'value' => $value, 'type' => is_array( $token ) ? $token[0] : null,
				'start' => $offset, 'end' => $end, 'depth' => $depth,
			];
			if ( in_array( $text, [ '(', '[', '{' ], true ) ) {
				$depth++;
			} elseif ( in_array( $text, [ ')', ']', '}' ], true ) ) {
				$depth--;
			}
		}
		$offset = $end;
	}
	return $result;
}

function legacyStatementMatches( array $tokens, string $statement ): array {
	$fingerprint = array_column( legacyTokens( "<?php\n" . $statement ), 'value' );
	$values = array_column( $tokens, 'value' );
	$length = count( $fingerprint );
	$matches = [];
	for ( $i = 0; $i <= count( $tokens ) - $length; $i++ ) {
		if ( array_slice( $values, $i, $length ) === $fingerprint ) {
			$matches[] = [
				'start' => $tokens[$i]['start'],
				'end' => $tokens[$i + $length - 1]['end'],
				'topLevel' => $tokens[$i]['depth'] === 0 &&
					( $i === 0 || in_array( $values[$i - 1], [ ';', '}' ], true ) ),
			];
		}
	}
	return $matches;
}

function loadingSignatures(): array {
	// Fresh WBS 7 LocalSettings.php, from wikibase@7.1.0. Installations upgraded
	// from earlier versions may still use the older section below.
	$wbs7MediaWiki = "require_once '/LocalSettings.MediaWiki.php';";
	$wbs7Extensions = "require_once '/LocalSettings.Extensions.php';";

	// The generated extension section is byte-identical in the WBS 1–6
	// LocalSettings.wbs.php templates (deploy@1.0.0 through deploy@6.0.0).
	$wbs1To6Extensions = <<<'PHP'
foreach (glob("LocalSettings.d/*.php") as $filename)
{
	include $filename;
}
PHP;
	return [ $wbs7MediaWiki, $wbs7Extensions, $wbs1To6Extensions ];
}

function failUnrecognizedLoadingSection(): never {
	$message = <<<'MESSAGE'
Your config/LocalSettings.php could not be migrated automatically for use with
this version of the Wikibase image. The file is unchanged.

The migration expects one of the following settings-loading sections in your
LocalSettings.php, as generated by earlier Wikibase images:

  For WBS 7:
  # Managed by the Wikibase image. DO NOT REMOVE OR MOVE THIS LINE.
  require_once '/LocalSettings.MediaWiki.php';

  # Add MediaWiki configuration values here that must be set before bundled
  # extensions are loaded.

  # Managed by the Wikibase image. DO NOT REMOVE OR MOVE THIS LINE.
  require_once '/LocalSettings.Extensions.php';

  For WBS 1–6 (including installations later upgraded to WBS 7):
  # Load extensions if present, alphabetically ordered by filename
  foreach (glob("LocalSettings.d/*.php") as $filename)
  {
      include $filename;
  }

Compare your file with these examples. If you can restore its original
settings-loading section, retry docker compose up -d. Do not add a second
copy of either section.

For additional help from the Wikibase Suite team, open a ticket at:
https://phabricator.wikimedia.org/maniphest/task/edit/form/129/
MESSAGE;
	fwrite( STDERR, "$message\n" );
	// Distinguish an untouched recognition failure from later migration errors.
	exit( 2 );
}

function adaptLegacyPrefix( string $prefix ): array {
	$tokens = legacyTokens( $prefix );
	[ $mediaWikiSignature, $extensionsSignature, $inlineSignature ] = loadingSignatures();
	$mediaWiki = legacyStatementMatches( $tokens, $mediaWikiSignature );
	$extensions = legacyStatementMatches( $tokens, $extensionsSignature );
	// The WBS 1–6 layout can survive in a WBS 7 installation after upgrades.
	$loop = legacyStatementMatches( $tokens, $inlineSignature );
	$extensionReplacement = "require '" . dirname( dirname( __DIR__ ) ) . "/config/LoadExtensions.php';";
	if ( count( $mediaWiki ) === 1 && count( $extensions ) === 1 && $loop === [] &&
		$mediaWiki[0]['topLevel'] && $extensions[0]['topLevel'] &&
		$mediaWiki[0]['start'] < $extensions[0]['start']
	) {
		$replacements = [
			[ $extensions[0], $extensionReplacement ],
			[ $mediaWiki[0], "require '" . __DIR__ . "/Suite7Defaults.php';" ],
		];
		$shape = 'wbs-7';
	} elseif ( count( $loop ) === 1 && $loop[0]['topLevel'] && $mediaWiki === [] && $extensions === [] ) {
		$replacements = [ [ $loop[0], $extensionReplacement ] ];
		$shape = 'wbs-1-to-6';
	} else {
		failUnrecognizedLoadingSection();
	}
	// Replace from the end so the original offsets remain valid.
	foreach ( $replacements as [ $match, $replacement ] ) {
		$prefix = substr_replace( $prefix, $replacement, $match['start'], $match['end'] - $match['start'] );
	}
	return [ $prefix, $shape ];
}

function validateMigratedConfiguration( string $instancePath, string $customPath ): void {
	foreach ( [ $instancePath, $customPath ] as $path ) {
		if ( !is_readable( $path ) ) {
			fail( "The prepared configuration is missing $path." );
		}
	}
	$custom = file_get_contents( $customPath );
	if ( $custom === false ) {
		fail( "Could not read $customPath." );
	}
	if ( preg_match( '/^# End of generated LocalSettings\.php\r?$/m', $custom ) ) {
		fail( 'The prepared LocalSettings.php still has the historical generated-settings marker. ' .
			'Keep the original file for support to review.' );
	}
	// Scan the entire result, including user settings below the old marker.
	// Matching string tokens ignores harmless mentions in comments.
	$obsolete = [ '/LocalSettings.MediaWiki.php', '/LocalSettings.Extensions.php', 'LocalSettings.d/*.php' ];
	$tokens = legacyTokens( $custom );
	foreach ( $tokens as $index => $token ) {
		$path = trim( $token['value'], "'" );
		if ( !in_array( $path, $obsolete, true ) || $token['type'] !== T_CONSTANT_ENCAPSED_STRING ) {
			continue;
		}
		for ( $i = $index - 1; $i >= 0; $i-- ) {
			if ( in_array( $tokens[$i]['value'], [ ';', '{', '}' ], true ) ) {
				break;
			}
			$isFileLoader = in_array( $tokens[$i]['type'], [ T_REQUIRE, T_REQUIRE_ONCE, T_INCLUDE, T_INCLUDE_ONCE ], true );
			$isLegacyGlob = $path === 'LocalSettings.d/*.php' && $tokens[$i]['value'] === 'glob';
			if ( $isFileLoader || $isLegacyGlob ) {
				fail( 'The prepared LocalSettings.php still contains an active WBS 1–7 loader. ' .
					'Keep the original file for support to review.' );
			}
		}
	}
}

function inheritedAnonymousPermissions( array $actual, array $reference ): string {
	$settings = '';
	// Earlier installations did not load Suite7Defaults.php. Preserve their
	// effective anonymous-access policy before loading user-owned Extensions.php.
	foreach ( [ 'edit', 'createpage', 'createtalk', 'writeapi', 'createaccount' ] as $right ) {
		$value = $actual['wgGroupPermissions']['*'][$right] ?? false;
		if ( $value !== ( $reference['wgGroupPermissions']['*'][$right] ?? false ) ) {
			$settings .= "\$wgGroupPermissions['*']['$right'] = " . var_export( $value, true ) . ";\n";
		}
	}
	return $settings === '' ? '' : "# Anonymous-access settings retained from the WBS 1–6 configuration.\n$settings\n";
}

function legacyCustomTail( string $source, int $markerPosition ): string {
	$lineEnd = strpos( $source, "\n", $markerPosition );
	$tail = $lineEnd === false ? '' : substr( $source, $lineEnd + 1 );
	$generatedFooters = [
		"##############################################################################\n\n" .
			"# Add configuration values below which should be set after extensions are loaded\n",
		"##############################################################################\n\n" .
			"# Add MediaWiki or extension configuration values here that should be set after\n" .
			"# bundled extensions are loaded.\n",
	];
	foreach ( $generatedFooters as $footer ) {
		if ( str_starts_with( ltrim( $tail, "\r\n" ), $footer ) ) {
			return substr( ltrim( $tail, "\r\n" ), strlen( $footer ) );
		}
	}
	return $tail;
}

function stageInstanceSettings( string $legacyPath, string $actualJsonPath, string $instancePath ): void {
	$actual = readJsonObject( $actualJsonPath );
	$source = file_get_contents( $legacyPath );
	if ( $source === false ) {
		fail( "Could not read $legacyPath." );
	}
	atomicWrite( $instancePath, phpAssignments( $actual, legacyElasticsearchHost( $source ) ) );
}

function writeLoadableLegacyConfiguration( string $legacyPath, string $prefixPath ): void {
	$source = file_get_contents( $legacyPath );
	if ( $source === false ) {
		fail( "Could not read $legacyPath." );
	}
	$markerPosition = legacyGeneratedMarkerPosition( $source );
	$lineEnd = strpos( $source, "\n", $markerPosition );
	$prefix = $lineEnd === false ? $source : substr( $source, 0, $lineEnd + 1 );
	[ $prefix, $shape ] = adaptLegacyPrefix( $prefix );
	atomicWrite( $prefixPath, $prefix );
	echo "$shape\n";
}

function stageMigratedConfiguration(
	string $legacyPath,
	string $actualJsonPath,
	string $referenceJsonPath,
	string $customPath,
	string $instanceTemporaryPath,
	string $instancePath
): void {
	$actual = readJsonObject( $actualJsonPath );
	$reference = readJsonObject( $referenceJsonPath );
	$source = file_get_contents( $legacyPath );
	if ( $source === false ) {
		fail( "Could not read $legacyPath." );
	}
	$markerPosition = legacyGeneratedMarkerPosition( $source );
	$beforeMarker = substr( $source, 0, $markerPosition );
	$customTail = legacyCustomTail( $source, $markerPosition );
	$instanceLookup = array_fill_keys( INSTANCE_KEYS, true );
	$migratedAssignments = [];
	foreach ( assignmentsInSourceOrder( $beforeMarker ) as $assignment ) {
		$name = $assignment['name'];
		if ( isset( $instanceLookup[$name] ) ) {
			continue;
		}
		if ( !array_key_exists( $name, $reference ) || !array_key_exists( $name, $actual ) || $actual[$name] !== $reference[$name] ) {
			$migratedAssignments[] = $assignment['source'];
		}
	}
	[ , $shape ] = adaptLegacyPrefix( substr( $source, 0, $markerPosition ) );
	$custom = customSettingsPreamble(
		$shape === 'wbs-1-to-6' ? inheritedAnonymousPermissions( $actual, $reference ) : ''
	);
	$custom .= "\n# Settings migrated from the generated WBS 1–7 LocalSettings.php.\n";
	$custom .= "# Some may be legacy values; review them after the upgrade.\n";
	$custom .= "# Review the backup for custom executable PHP above the old generated marker.\n";
	if ( $migratedAssignments !== [] ) {
		$custom .= "\n" . implode( "\n\n", $migratedAssignments ) . "\n";
	}
	if ( trim( $customTail ) !== '' ) {
		$custom .= "\n# Custom configuration preserved from below the old generated marker.\n";
		$custom .= ltrim( $customTail );
	}
	atomicWrite( $customPath, $custom );
	if ( !rename( $instanceTemporaryPath, $instancePath ) ) {
		fail( "Could not install $instancePath." );
	}
	chmod( $instancePath, 0644 );
}

function installStagedFile( string $sourcePath, string $destinationPath ): void {
	$contents = file_get_contents( $sourcePath );
	if ( $contents === false ) {
		fail( "Could not read staged configuration $sourcePath." );
	}
	atomicWrite( $destinationPath, $contents );
}

$command = $argv[1] ?? '';
switch ( $command ) {
	case 'stage-instance-settings':
		if ( count( $argv ) !== 5 ) {
			fail( 'Usage: MigrateConfiguration.php stage-instance-settings LEGACY ACTUAL_JSON INSTANCE' );
		}
		stageInstanceSettings( $argv[2], $argv[3], $argv[4] );
		break;
	case 'write-loadable-legacy-config':
		if ( count( $argv ) !== 4 ) {
			fail( 'Usage: MigrateConfiguration.php write-loadable-legacy-config LEGACY OUTPUT' );
		}
		writeLoadableLegacyConfiguration( $argv[2], $argv[3] );
		break;
	case 'stage-migrated-configuration':
		if ( count( $argv ) !== 8 ) {
			fail( 'Usage: MigrateConfiguration.php stage-migrated-configuration LEGACY ACTUAL_JSON REFERENCE_JSON CUSTOM INSTANCE_TEMP INSTANCE' );
		}
		stageMigratedConfiguration( $argv[2], $argv[3], $argv[4], $argv[5], $argv[6], $argv[7] );
		break;
	case 'install':
		if ( count( $argv ) !== 4 ) {
			fail( 'Usage: MigrateConfiguration.php install SOURCE DESTINATION' );
		}
		installStagedFile( $argv[2], $argv[3] );
		break;
	case 'validate':
		if ( count( $argv ) !== 4 ) {
			fail( 'Usage: MigrateConfiguration.php validate INSTANCE CUSTOM' );
		}
		validateMigratedConfiguration( $argv[2], $argv[3] );
		break;
	default:
		fail( 'Expected stage-instance-settings, write-loadable-legacy-config, stage-migrated-configuration, validate, or install.' );
}
