# traefik dynamic configuration

http:
  services:
    wikibase:
      loadBalancer:
        servers:
          - url: "http://wikibase:80"

    wdqs-qlever-proxy:
      loadBalancer:
        servers:
          - url: "http://wdqs-qlever-proxy:8090"

    wdqs-frontend:
      loadBalancer:
        servers:
          - url: "http://wdqs-frontend:80"

    quickstatements:
      loadBalancer:
        servers:
          - url: "http://quickstatements:80"

  routers:
    wikibase-router:
      rule: 'Host(`{{ env "WIKIBASE_PUBLIC_HOST" }}`) && !PathPrefix(`/tools`)'
      service: wikibase

    wdqs-qlever-proxy-router:
      rule: 'Host(`{{ env "WDQS_PUBLIC_HOST" }}`) && PathPrefix(`/sparql`) && (Method(`GET`) || Method(`OPTIONS`) || Method(`POST`))'
      service: wdqs-qlever-proxy
      middlewares: [ wdqs-qlever-proxy-headers, wdqs-qlever-proxy-cors-headers, wdqs-qlever-proxy-rate-limit ]

    wdqs-frontend-router:
      rule: 'Host(`{{ env "WDQS_PUBLIC_HOST" }}`) && !PathPrefix(`/sparql`)'
      service: wdqs-frontend

    quickstatements-router:
      rule: 'Host(`{{ env "WIKIBASE_PUBLIC_HOST" }}`) && PathPrefix(`/tools/quickstatements`)'
      service: quickstatements
      middlewares: [ quickstatements-redirectregex, quickstatements-stripprefix ]

  middlewares:
    wdqs-qlever-proxy-headers:
      headers:
        accessControlAllowMethods: "GET,OPTIONS,POST"
        customResponseHeaders:
          VARY: Accept

    wdqs-qlever-proxy-cors-headers:
      headers:
        accessControlAllowHeaders: "*"

    wdqs-qlever-proxy-rate-limit:
      rateLimit:
        burst: 30
        average: 60
        period: 1m

    quickstatements-redirectregex:
      redirectRegex:
        regex: /tools/quickstatements$
        replacement: /tools/quickstatements/
        permanent: true

    quickstatements-stripprefix:
      stripPrefix:
        prefixes: [ /tools/quickstatements ]
