#!/usr/bin/env bash
set -euo pipefail

# --- Expected Variables ---

export DEPLOY_DIR
export ENV_FILE_PATH
export LOCALHOST
export DEBUG
export SCRIPTS_DIR

# ---------- Script Specific Setup ----------

# Setup defaults from template
TEMPLATE_PATH="${TEMPLATE_PATH:-$DEPLOY_DIR/template.env}"
declare -A defaults
while IFS='=' read -r key val; do
  [[ -z "$key" || "$key" =~ ^# ]] && continue
  defaults[$key]="${val}"
done < "$TEMPLATE_PATH"

# Setup config text
CONFIG_TEXT="# Autogenerated from setup UI based on $(basename "$TEMPLATE_PATH")"$'\n'
_append_config() { CONFIG_TEXT="$CONFIG_TEXT"$"$1=$2"$'\n'; }

# Show server's IP address to help DNS registration step
if ! $LOCALHOST; then
  SERVER_IP=$(curl -fsSL https://api.ipify.org)
  echo Public IP of your server is: "$SERVER_IP"
  echo
fi

# ---------- Gather Inputs ----------

# UI + validators library 
# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/_prompt-ui.sh"

ui_prompt_until MW_ADMIN_EMAIL "MediaWiki ${defaults[MW_ADMIN_NAME]} user email" ui_valid_email

$LOCALHOST && WIKIBASE_PUBLIC_HOST="wikibase.test"
ui_prompt_until WIKIBASE_PUBLIC_HOST "Wikibase host, e.g. example.com or *.test" ui_host_is_valid

[[ -z "${WDQS_PUBLIC_HOST:-}" ]] && WDQS_PUBLIC_HOST="query.${WIKIBASE_PUBLIC_HOST}"
ui_prompt_until WDQS_PUBLIC_HOST "Query Service host" ui_host_is_valid true

# Passwords (blank ⇒ auto-generate; enforce min length ≥ 10 if provided)
ui_prompt_masked MW_ADMIN_PASS "MediaWiki admin password (auto-generate)" 10
[[ -z "${MW_ADMIN_PASS:-}" ]] && MW_ADMIN_PASS="$(ui_generate_password)"

ui_prompt_masked DB_PASS "Database password (auto-generate)" 10
[[ -z "${DB_PASS:-}" ]] && DB_PASS="$(ui_generate_password)"

# Yes/No with default Yes. (This prints one newline after, by design.)
ui_yes_no METADATA_CALLBACK "Make this Wikibase visible in the global directory?" Y

_append_config MW_ADMIN_EMAIL        "$MW_ADMIN_EMAIL"
_append_config WIKIBASE_PUBLIC_HOST  "$WIKIBASE_PUBLIC_HOST"
_append_config WDQS_PUBLIC_HOST      "$WDQS_PUBLIC_HOST"
_append_config MW_ADMIN_NAME         "${defaults[MW_ADMIN_NAME]}"
_append_config MW_ADMIN_PASS         "$MW_ADMIN_PASS"
_append_config DB_NAME               "${defaults[DB_NAME]}"
_append_config DB_USER               "${defaults[DB_USER]}"
_append_config DB_PASS               "$DB_PASS"
_append_config METADATA_CALLBACK     "$METADATA_CALLBACK"

printf "%s" "$CONFIG_TEXT" > "$ENV_FILE_PATH"
