#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PARENT_DIR="$(cd "$ROOT_DIR/.." && pwd)"
WBS_DIR="${WBS_DIR:-$PARENT_DIR}"
DEPLOY_DIR="${DEPLOY_DIR:-$WBS_DIR/wikibase-release-pipeline/deploy}"
ENV_FILE_PATH="${ENV_FILE_PATH:-$DEPLOY_DIR/.env}"
LOG_PATH="${LOG_PATH:-/tmp/wbs-deploy-setup.log}"

usage() {
  cat <<EOF
Usage:
  $(basename "$0")            Seed a fake completed setup state for local UI testing
  $(basename "$0") --reset    Remove the fake state

Environment overrides:
  WBS_DIR
  DEPLOY_DIR
  ENV_FILE_PATH
  LOG_PATH
EOF
}

if [[ "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ "${1:-}" == "--reset" ]]; then
  rm -f "$ENV_FILE_PATH"
  : > "$LOG_PATH"
  echo "Reset fake setup state:"
  echo "  removed $ENV_FILE_PATH"
  echo "  cleared $LOG_PATH"
  exit 0
fi

mkdir -p "$(dirname "$ENV_FILE_PATH")"
mkdir -p "$(dirname "$LOG_PATH")"

cat > "$ENV_FILE_PATH" <<'EOF'
# Autogenerated fake config for local completion-screen testing
MW_ADMIN_EMAIL=you@example.org
MW_ADMIN_NAME=Admin
WIKIBASE_PUBLIC_HOST=wikibase.test
WDQS_PUBLIC_HOST=query.wikibase.test
METADATA_CALLBACK=true
MW_ADMIN_PASS=LocalDevAdminPass123!
DB_NAME=my_wiki
DB_USER=sqluser
DB_PASS=LocalDevDatabasePass123!
EOF

cat > "$LOG_PATH" <<'EOF'
2026-01-01T12:00:00Z [status] Configuration saved.
2026-01-01T12:00:10Z [status] Waiting for services to start. Generally takes 2–6 minutes...

✅ Setup is Complete!
EOF

echo "Seeded fake completed setup state:"
echo "  wrote $ENV_FILE_PATH"
echo "  wrote $LOG_PATH"
echo
echo "Reload the setup page and it should show the completion screen."
